/**
# Initializing an interface using a 1D spectrum

To initialize an interface using a 2D spectum see
[here](initial_conditions_dimonte_fft2.h).

To initialize the interface we'll use a 1 Fourier transform and some
interpolation routines from `GSL`.
*/

#include <gsl/gsl_fft_complex.h>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_spline.h>
#pragma autolink -lgsl -lgslcblas
#define REAL(z,i) ((z)[2*(i)])
#define IMAG(z,i) ((z)[2*(i)+1])

/**
## Save the initial perturbation in a gnuplot-compatible format 
### *save_data_for_gnuplot_complex()*: saves a (complex) 1D array as a .dat file
*/

void save_data_for_gnuplot_complex(double *data, int NX, const char *filename){
  FILE *file = fopen(filename, "w");
  if (file == NULL){
    fprintf(stderr, "Error opening file %s\n", filename);
    return;
  }

  for (int i = 0; i < NX; i++){
    double kx = (i <= NX / 2) ? (2. * pi * i / L0) : (2. * pi * (i - NX) / L0);
    double magnitude = sqrt(sq(REAL(data, i)) + sq(IMAG(data, i)));
    fprintf(file, "%d %g %f %f %f\n", i, kx, REAL(data,i), IMAG(data,i), magnitude);
  }
  fclose(file);
}

/** 
### *save_data_for_gnuplot_real()*: saves a 1D array as a .dat file
*/
void save_data_for_gnuplot_real(double *data, int NX, const char *filename){
  FILE *file = fopen(filename, "w");
  if (file == NULL){
    fprintf(stderr, "Error opening file %s\n", filename);
    return;
  }

  for (int i = 0; i < NX; i++){
    fprintf(file, "%d %f \n", i, data[i]);
  }
  fclose(file);
}

/** 
## Generate the perturbation in Fourier space and return to physical space 
### *init_1D_complex()*: initializes the perturbation in Fourier space
*/

void init_1D_complex(double *data, size_t N, double kmin, double kmax, double eta0_target=1){
  double *kx = malloc(N * sizeof(double));
  double cst;
  cst = eta0_target;

  // Calculate wavenumbers
  for (int i = 0; i <= N / 2; ++i)
    kx[i] = 2 * pi * i / L0;

  for (int i = N / 2 + 1; i < N; ++i)
    kx[i] = 2 * pi * (i - N) / L0;

  // Initialize spectrum in the specified range with magnitude 1/k and random
  // phase. To ensure the inverse FFT produces real values, we enforce
  // Hermitian symmetry: F[N-k] = conj(F[k])
  double eta0_spectral = 0.;  // Spectral energy for Parseval check
  memset(data, 0, 2 * N * sizeof(double));
  
  // Zero frequency is always zero. 
  // Handle positive frequencies (i = 1 to N/2)
  for (int i = 1; i <= N / 2; ++i){
    double k = fabs(kx[i]);
    if ((k >= kmin) && (k <= kmax)){
      double magnitude = cst / sqrt(k);
      double phase = noise() * pi;
      REAL(data, i) = magnitude * cos(phase);
      IMAG(data, i) = magnitude * sin(phase);
      
      // For Parseval with GSL's unnormalized backward FFT:
      // Var_real = (1/N) Σ|f[n]|² = Σ|F[k]|² (summing over all k including negatives)
      // Since we set both F[k] and F[-k], we count the contribution once here
      if (i < N / 2) {  
        // Regular modes: both +k and -k contribute, so count 2×|F[k]|²
        eta0_spectral += 2.0 * sq(magnitude);
      } else {  
        // Nyquist frequency appears once
        eta0_spectral += sq(magnitude);
      }
      
      // Set the negative frequency to be the complex conjugate
      if (i < N / 2) {  
        // Don't duplicate Nyquist frequency
        int neg_i = N - i;
        REAL(data, neg_i) = REAL(data, i);   // Real part stays the same
        IMAG(data, neg_i) = -IMAG(data, i);  // Imaginary part is negated
      }
    }    
  }
  fprintf(stdout, "Spectral RMS (Parseval): %g \n", sqrt(eta0_spectral));
  
  // Post-normalization: scale to achieve exact target RMS
  if (eta0_spectral > 0) {
    double scale = eta0_target / sqrt(eta0_spectral);
    for (int i = 0; i < N; ++i) {
      REAL(data, i) *= scale;
      IMAG(data, i) *= scale;
    }
    eta0_spectral *= sq(scale);  // Update spectral energy after rescaling
    fprintf(stdout, "Rescaled by factor %g to achieve target RMS = %g\n", scale, eta0_target);
  }

  free(kx);
}


/** 
## Apply the initial condition to a scalar field
### *initial_condition_dimonte_fft()*: initializes a scalar field f 

This function initializes a scalar field `phi` with a perturbation generated
using a 1D Fast Fourier Transform (FFT). The perturbation is generated by the
main process and broadcasted to other processes if MPI is used. The perturbation
can be applied directly to the field or used to generate a Volume of Fluid (VOF)
surface. 

The arguments and their default values are:

*phi*
: vertex scalar field to be initialized.

*amplitude*
: amplitude of the perturbation. Default is *1*.

*NX*
: number of points along the x-dimension. Default is *N*.

*kmin*
: minimum wavenumber for the perturbation. Default is *1*.

*kmax*
: maximum wavenumber for the perturbation. Default is *1*.


#### Example Usage

```c
initial_condition_dimonte_fft(phi, 0.5, 128, 0.1, 10.0);
```

see, also [example](test_init_fft4.c).

*/
void initial_condition_dimonte_fft(vertex scalar phi, double amplitude=1, int NX=N, double kmin=1, double kmax=1, bool isvertex=1){
  
  // We declare the arrays and initialize the physical space
  double *data = malloc(2 * NX * sizeof(double));
  double *xdata = (double *)malloc(NX * sizeof(double));
  double *ydata = (double *)malloc(NX * sizeof(double));

  double dx = L0 / NX;
  for (int i = 0; i < NX; i++){
    xdata[i] = i * dx + X0;
  }

  // The perturbation is generated only by the main process
  if (pid() == 0){
    // Initialize the spectrum
    init_1D_complex(data, NX, kmin, kmax, eta0_target=amplitude);
    save_data_for_gnuplot_complex(data, NX, "initial_spectra.dat");

    /** Perform the inverse FFT. We use the mixed-radix routine rather than
    `gsl_fft_complex_radix2_backward()` since the latter requires *NX* to be a
    power of two. The mixed-radix version accepts any *NX*, at the cost of
    allocating a wavetable and a workspace. */
    gsl_fft_complex_wavetable *wavetable = gsl_fft_complex_wavetable_alloc(NX);
    gsl_fft_complex_workspace *workspace = gsl_fft_complex_workspace_alloc(NX);
    gsl_fft_complex_backward(data, 1, NX, wavetable, workspace);
    gsl_fft_complex_wavetable_free(wavetable);
    gsl_fft_complex_workspace_free(workspace);
    save_data_for_gnuplot_complex(data, NX, "final_deformation.dat");

    // Save the results into a 2D array
    for (int i = 0; i < NX; i++){
      ydata[i] = REAL(data,i);
    }
    
    // Verify Parseval's theorem: compute RMS in real space
    double mean_real = 0.;
    for (int i = 0; i < NX; i++){
      mean_real += ydata[i];
    }
    mean_real /= NX;
    
    double variance_real = 0.;
    for (int i = 0; i < NX; i++){
      variance_real += sq(ydata[i] - mean_real);
    }
    variance_real /= NX;
    double eta0_real = sqrt(variance_real);
    
    fprintf(stdout, "Real space RMS (after IFFT): %g\n", eta0_real);
    fprintf(stdout, "Parseval check: spectral vs real space energy ratio = %g\n", 
            eta0_real / amplitude);
    
    save_data_for_gnuplot_real(ydata, NX, "final_deformation2.dat");
  }

  // and broadcasted to the other processes if MPI
  @ if _MPI
    MPI_Bcast(ydata, NX, MPI_DOUBLE, 0, MPI_COMM_WORLD);
  @endif

  /** Create a 3-tile array to handle periodicity properly.
  The center tile contains the original domain [X0, X0+L0].
  The left and right tiles are periodic copies, ensuring the interpolator
  has data on both sides even near the boundaries.
  */
  int NX_tiled = 3 * NX;
  double *xdata_tiled = (double *)malloc(NX_tiled * sizeof(double));
  double *ydata_tiled = (double *)malloc(NX_tiled * sizeof(double));

  // Create tiled coordinate and data arrays: 3 copies shifted by -L0, 0, +L0
  for (int i = 0; i < NX_tiled; i++) {
    xdata_tiled[i] = xdata[i % NX] + ((i / NX) - 1) * L0;
    ydata_tiled[i] = ydata[i % NX];
  }

  // Now, we'll interpolate the perturbation into the mesh using the tiled data
  gsl_interp *interp = gsl_interp_alloc(gsl_interp_linear, NX_tiled);
  gsl_interp_accel *acc = gsl_interp_accel_alloc();

  // Initialize the interpolation object with tiled data
  gsl_interp_init(interp, xdata_tiled, ydata_tiled, NX_tiled);

  /** Apply initial condition to the scalar field. Here, we take care to
  normalize the perturbation using the standard deviation and multiply it by
  some amplitude.
  */
  
  if (isvertex){
    foreach_vertex()
      phi[] = gsl_interp_eval(interp, xdata_tiled, ydata_tiled, x, acc) - y;
  }
  else {
    foreach()
      phi[] = gsl_interp_eval(interp, xdata_tiled, ydata_tiled, x, acc) - y;
  }  

  // Release interpolation objects
  gsl_interp_free(interp);
  gsl_interp_accel_free(acc);

  // Free Dynamically Allocated Memory
  free(xdata);
  free(ydata);
  free(xdata_tiled);
  free(ydata_tiled);
  free(data);
}
