/**
# Sloshing as a damped oscillator

We analyse the dissipation of stationnary (linear) waves in a tank. This simulation only takes into account the bulk dissipation. To take into account the dissipation generated at the wall, go [there](/sandbox/MCVacher/slosh_dissipation_wall.c).

The code has dimensions as it is right now.

We use "harmonic.h" to check the theoretical sloshing frequency.

Check Antoine Aubert's sandbox [here](/sandbox/aaubert/). He helped me building this case, many thanks to him. 

## Simulation
*/

#include "grid/multigrid.h"
#include "navier-stokes/centered.h"
#include "two-phase.h"
#include "navier-stokes/conserving.h"
#include "navier-stokes/perfs.h"
#include "harmonic.h"

double omegas[3];

double h;
double h_1;
double R;
double mu_b;
double rho_b;
double grav;

FILE * fpmax; //

int main() {

  L0=0.4; //size of the box
  rho2 = 1.3;
  rho1=1000;
  mu1 = 0.5;
  mu2 = 0.001*mu1;
  h=0.15; //water height at rest
  grav=9.81;
  
  h_1=0.02; //size of the perturbation

  TOLERANCE = 1e-3 [*];
  
  /**
  Slip conditions are considered so that we measure only the dissipation generated by the bulk.
  */

  u.n[bottom] = dirichlet(0.);
  u.t[bottom] = neumann(0.);

  u.n[top] = neumann(0.);
  p[top] = dirichlet(0.);

  u.n[left] = dirichlet(0.);
  u.n[right] = dirichlet(0.);
  u.t[left] = neumann(0.);
  u.t[right] = neumann(0.);
 
  N=128;
  origin (-L0/2, 0);
  init_grid(N);
  
  char param_dim[80];
  sprintf (param_dim, "param_dim.txt");
  FILE * fparam = fopen(param_dim, "w");
  fprintf (fparam, "%g %g %g %g %g %g %g %d\n",L0,h,R,rho1,rho2,mu1,mu2,N);
  fclose (fparam);

  fpmax =  fopen("log.dat", "w");

  run();
}

/**
The initial state is a sloshing mode $m=3$, of amplitude $h_1$.
*/

event init (t = 0) {
  mu_b=mu2/mu1;
  rho_b=rho2/rho1;
  R=h/L0;

  char dim_adim[80];
  sprintf (dim_adim, "dim_adim.txt"); //to compute the non-dim. parameters
  FILE * fparam = fopen(dim_adim, "w");
  fprintf (fparam, "%g %g %g\n",mu_b,rho_b,R);
  fclose (fparam);

  fraction (f, h_1*sin(3*M_PI*x/L0)+h-y);
  const face vector G[] = {0,-grav};
  a=G;
  
  /**
  We compute the theoretical sloshing frequencies (pseudo-pulsation in case of viscosity)
  */
  
  double lamb1 = 2.0*mu1/rho1*pow(M_PI/L0,2);
  double lamb3 = 2.0*mu1/rho1*pow(3.0*M_PI/L0,2);
  double f1 = sqrt(1.0*grav/(4.0*M_PI*L0) * tanh(M_PI*h/L0));
  double f3 = sqrt(3.0*grav/(4.0*M_PI*L0) * tanh(3.0*M_PI*h/L0));
  omegas[0] = 2.0*M_PI*f1*(sqrt(1-pow(lamb1/(2.0*M_PI*f1),2)));
  omegas[1] = 2.0*M_PI*f3*(sqrt(1-pow(lamb3/(2.0*M_PI*f3),2)));
  //omegas[0] = 2.0*M_PI*f1;
  //omegas[1] = 2.0*M_PI*f3;
  omegas[2] = 0.0;
}

event logfile (i++) { 
  fprintf (stderr, "%d %g \n", i, t);
  fprintf (fpmax, "%d %g \n", i, t);
}


/**
 We use harmonic.h and perform it on u.y at the chosen $\omega_n$.
*/

event harmonic_analysis (t += 0.01; t <= 15) {
  harmonic_decomposition(u.y, t, omegas);
}


event profile (t = end) {
  printf ("-----END-----\n");
}

/**
We track the interface to compute the logarithmic decrease linked to the viscous dissipation.
*/

int isave1 = 1;
event res_save (t += 0.005; t <= 15){

  char name[80];
  
  sprintf (name, "interface-%d.txt", isave1);
  FILE * fpfacet = fopen(name, "w");
  output_facets (f, fpfacet);
  fclose(fpfacet);

  isave1++;
}

/**
We generate a video of the fraction to visualize the decreasing sloshing, as well as videos using "harmonic.h".
*/

event ppm_output (t = 0; t += 0.01; t <= 15) {

  char name[80];
  sprintf (name, "f.mp4");
  output_ppm (f, file = name, n = 512, min = 0, max = 1, linear = true);

  // amplitude for mode 1 (omegas[0])
  scalar amp_mode_1[];
  int k1 = 0;
  foreach()
    amp_mode_1[] = sqrt(sq(val(u.y.harmonic.A[k1])) + sq(val(u.y.harmonic.B[k1])));
  boundary ({amp_mode_1});
  char name_u_1[80];
  sprintf(name_u_1, "u_y_1.mp4");
  output_ppm(amp_mode_1, file = name_u_1, n = 512, min = 0, max = 0.1, linear = true);

  // amplitude for mode 3 (omegas[1])
  scalar amp_mode_3[];
  int k3 = 1;
  foreach()
    amp_mode_3[] = sqrt(sq(val(u.y.harmonic.A[k3])) + sq(val(u.y.harmonic.B[k3])));
  boundary ({amp_mode_3});
  char name_u_3[80];
  sprintf(name_u_3, "u_y_3.mp4");
  output_ppm(amp_mode_3, file = name_u_3, n = 512, min = 0, max = 0.1, linear = true);
  
  //u.y
  char name_u[80];
  sprintf (name_u, "u_y.mp4");
  output_ppm (u.y, file = name_u, n = 512,min = -0.3, max = 0.3, linear = true);
}

/**
![Waves](slosh_dissipation/f.mp4)
*/

/**
## Comparison with theory : damping due to bulk dissipation

For the full derivation of the formulas, go [there]() *soon*

We find in the end that the amplitude of the oscillation $\eta_0$ is following a logarithmic decrement, such as :

$$\frac{\text{d} \eta_0}{\text{d} t} + \lambda_1\eta_0 = 0$$

with:

$$\lambda_1 = 2\nu k_m^2 \tanh(k_m h_0)$$

and with $k_m$ the wave number of the sloshing mode $m$:

$$ k_m = \frac{m\pi}{L}$$

Consequently we have:


$$\eta_0(t) = \eta_0(0)\exp(-\lambda_1 t)$$


**Note :** In *Hydrodynamics* by Lamb, only the case $h_0 \rightarrow +\infty$ is computed, which gives $\lambda_1 = 2\nu k_m^2$ as expected (§ 348).

~~~pythonplot Comparison with theory
import sys
sys.path.insert(0, 'C:/Users/M3051168/Documents/Analyse_exp_data/Codes') 

import matplotlib.pyplot as plt
import numpy as np
import glob as gb
import re
import os
from scipy.signal import find_peaks

#####################Init######################
l_x_surf_app=[]
l_y_surf_app=[]

listeFichiersTxt_1=sorted(gb.glob('interface'+'*.txt'),key=str.casefold) 
listeFichiersTxt_1.sort(key=lambda f: int(re.search(r'\d+', f).group()))

###############################################

for ind_fichier in range(1,len(listeFichiersTxt_1)):
    list_x_surf=[]
    list_y_surf=[]
    time_name=listeFichiersTxt_1[ind_fichier]
    with open(time_name, encoding='utf8') as File:
        for line in File:
            if line.isspace()==0:
                temp=line.split()
                x=float(temp[0])
                list_x_surf.append(x)
                y=float(temp[1])
                list_y_surf.append(y)
        File.close()

    l_x_surf_app.append(list_x_surf)
    l_y_surf_app.append(list_y_surf) 

liste_decrease=[]

for i in range(len(l_y_surf_app)):
        liste_decrease.append(max(l_y_surf_app[i][:])-0.15)
        
corr=liste_decrease[-1]

for i in range(len(l_y_surf_app)):
        liste_decrease[i]=liste_decrease[i]-corr

x=np.linspace(0,15,len(liste_decrease))
y=liste_decrease

peaks, _ = find_peaks(y)
x_peaks = [x[element] for element in peaks]
y_peaks = [y[element] for element in peaks]

nu=0.5/1000
L=0.4
m=3
h=0.15

k_m=m*np.pi/L

lamb=2*nu*(k_m)**2*np.tanh(k_m*h)

plt.figure()
plt.plot(x_peaks,y_peaks,'r*',label='Num.')
plt.plot(x,[0.025*np.exp(-lamb*elem) for elem in x],label='Theory')
plt.legend()
plt.savefig('decreasing.png')
~~~

*/

/**
We have the theoretical pulsation of the sloshing mode:

$$\omega_m = \sqrt{\frac{m\pi g}{L}\tanh (m\pi\frac{h_0}{L})}$$

With viscosity, it is the pseudo-pulsation that is important:

$$\omega_p = \omega_m \times \sqrt{1-\frac{\lambda_1^2}{\omega_m^2}}$$

To verify this, we use [harmonic.h](/src/harmonic.h), that performs a least-square fit between a scalar field (here we take the vertical velocity u.y) and Fourier decomposition, such as :

$$ \forall \omega_i \in \Omega_{test}, \tilde{u_y}(x,y) = Z(x,y) + Z + \sum_i A_i(x,y) \cos(\omega_i t) + B_i(x,y) \sin(\omega_i t),$$

$\tilde{u_y}$ being the regression. 

Here is the principle of this decomposition : if you have a strong periodic component associated with $\omega_i$, this component should be constant over time (see [here](/sandbox/MCVacher/test_harmonic.c)).

Hence, after the initial start, we observe that the component of the mode $m=3$ is nearly constant over time, because of the slow decreasing amplitude of the sloshing. However, the component of the mode $m=1$ is of an order of magnitude less, and aldo slowly decreasing.

*/

/**
![Vitesse verticale](slosh_dissipation/u_y.mp4)
![Projection de la norme de la vitesse verticale sur le mode n°3](slosh_dissipation/u_y_3.mp4)
![Projection de la norme de la vitesse verticale sur le mode n°1](slosh_dissipation/u_y_1.mp4)
*/