CFLAGS += -O2
include $(BASILISK)/Makefile.defs


rbi2d.tst: CC=mpicc -D_MPI=4

rbi2dsf.tst: CC=mpicc -D_MPI=4

rbi2dadpt.tst: CC=mpicc -D_MPI=2

rbi2dsfdiff.tst: rbi2dsfdiff.tst

rbvisco.tst: CC=mpicc -D_MPI=4

rbvisco3D.tst: CC=mpicc -D_MPI=4