/**
# Dam-break Wave Generation (Navier-Stokes)

This is the Navier-Stokes VOF case of the [Prins, 1958](#references) dam-break experiment. See the [multilayer case](prins.c) for details.

*/




#include <sys/stat.h>
#include "navier-stokes/centered.h"
#include "two-phase.h"
#include "navier-stokes/conserving.h"
#include "tension.h"
#include "reduced.h"
#include "/sandbox/oystelan/waveprobes.h"
#include "navier-stokes/perfs.h"
#include "view.h"
#define maxlevel 15
#define minlevel 3
#define MUR 54
#define SIGMA 73e-03
#define GRAVITY -9.81
#define L 0.09144	// 0.3 ft in m
#define H 0.15240	// 0.5 ft in m
#define Q 0.09144	// +0.3 ft in m
#define length 30.	// (30m = 98.4252 ft)
#define ENDTIME 30.



/**
The domain is length+L metres squared. */

int main() {
  struct stat st = {0};
  if (stat("./facets", &st) == -1) {
    mkdir("./facets", 0755);
  }
  size(length+L);
  origin (-L, -H);
  rho1 = 1000;
  rho2 = 1.27;
  mu1 = 1.002e-3;
  mu2 = mu1/MUR;
  f.sigma = SIGMA;
  G.y = GRAVITY;
  run(); 
}





/**
The simple initial geometry is instanced and a large portion of the void space above the domain of interest is masked. */

event init (t = 0)
{
  mask (y > 2.*H ? top : none);
  refine (y < Q*1.1 && level < maxlevel);
  foreach() {
    if ( (x < 0.) && (y < Q) )
      f[] = 1.;
    else if ( (x > 0.) && (y < 0.) )
      f[] = 1.;
    else
      f[] = 0.;
    foreach_dimension()
      u.x[] = 0.;
  }
  boundary({f,u.x,u.y});
}






/**
Statistics are generated along with numerical gauges placed as in the physical experiment, set to output at an arbitrary rate (50 Hz) */


event logfile (i++) {
  if (i == 0)
    fprintf (ferr,
	"t dt mgp.i mgpf.i mgu.i grid->tn perf.t perf.speed\n");
  fprintf (ferr, "%g %g %d %d %d %ld %g %g\n", 
      t, dt, mgp.i, mgpf.i, mgu.i,
      grid->tn, perf.t, perf.speed);
}

event waveprobes (t += 0.01) {
  heights (f,h);
  static FILE * fp0 = fopen("waveprobe.dat", "w");
  double xcoords[2]  = {-H,H};
  double xMax0 = wprobe(1.524,xcoords,200);//5ft
  double xMax1 = wprobe(4.572,xcoords,200);//15ft
  double xMax2 = wprobe(7.62,xcoords,200);//25ft
  double xMax3 = wprobe(10.668,xcoords,200);//35ft
  double xMax4 = wprobe(13.716,xcoords,200);//45ft
  fprintf(fp0, "%g %g %g %g %g %g\n", t, xMax0, xMax1, xMax2, xMax3, xMax4);
  fflush(fp0);
}





/**
The following is used to post-reconstruct the interface. */

event out_facets (t < 1.5; t += 0.05) {
  char name[60];
  sprintf(name, "facets/facets_t_%g.dat", t);
  FILE * fp_facet = fopen (name, "w");
  output_facets (f, fp_facet);
  fclose (fp_facet);
}


/**
The simulation is adapted using the following error criteria and is ended at a specific simulated time. */

event end (t = ENDTIME) {
}

event adapt (i++) {
  adapt_wavelet ({u,f}, (double[]){3e-2,3e-2,1e-2}, maxlevel);
}




/**
## Results

*(Must tidy for units, labels, key etc. or even replace with GNUplot)*

The leading crest or trough heights $\eta$ at the guages $x=5 ft$ and $x=25 ft$ are sufficiently comparable across the investigated range of $Q$ and $L$.

The experimental trend is plotted as the red dashed line.

<img src="https://upload.wikimedia.org/wikipedia/commons/2/2b/Prins_n_x5.png" alt="" width=350px/><img src="https://upload.wikimedia.org/wikipedia/commons/7/78/Prins_n_x25.png" alt="" width=350px/>

Additionally compared is the wave height $H$ of the first phase at $x=25 ft$.

<img src="https://upload.wikimedia.org/wikipedia/commons/5/50/Prins_H_x25.png" alt="" width=350px/>


And finally, an example of the time-period relationship of the model compared with the [Kranzer and Keller theory](#references) (black dashed lines for $x=5, 15, 25, 35).

<img src="https://upload.wikimedia.org/wikipedia/commons/5/5f/Prins_t-T.png" alt="" width=350px/>



/**
## References

H. C. Kranzer and J. B. Keller. Water waves produced by explosions. *Journal of Applied Physics*, 30(3), 398-407, March 1959.
\[ [DOI](https://doi.org/10.1063/1.1735176) | 
[http](https://aip.scitation.org/doi/10.1063/1.1735176)
\]

J. E. Prins. Characteristics of waves generated by a local disturbance. *Eos
Trans. AGU*, 39(5), 865–874, October 1958. 
\[ [DOI](https://doi.org/10.1029/TR039i005p00865) | 
[http](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/TR039i005p00865)
\]

*/


