include $(BASILISK)/Makefile.defs


# the default CFLAGS are set in ../config
CFLAGS += -O2 -DMTRACE=3



poiseuille.tst:CFLAGS+= 

Bingham.tst:CFLAGS+=

BagnoldDry.tst:CFLAGS+=

BagnoldCohesive.tst:CFLAGS+=