CFLAGS += -O2 -fopenmp
include $(BASILISK)/Makefile.defs


MAIN = beach_topo

# Cleanup of EVERYTHING (except scripts)
fullclean :
	rm *~ $(MAIN).c.tags $(MAIN).c.tags.d $(MAIN).s.d $(MAIN).s $(MAIN).tst Makefile.deps Makefile.tests $(MAIN)/* $(MAIN).c.html
