/**
## Surface wave generated by a submerged obstacle
*/
#include "embed.h"
#include "navier-stokes/centered.h"
#include "two-phase.h"
#include "reduced.h"
#include "navier-stokes/perfs.h"
#include "view.h"
#include "curvature.h"

int maxlevel = 7;
double Re, Fr, gg = 9.81, RHO = 1000.;
double U0= 0.5;
double Heau = 0.9, xo=8.;
double EndTime = 30.;  
  
/**
The profile of the bump is calculated with a Gaussian centred in xo
*/
#define bump ((1./(1.*sqrt(2*M_PI)))*exp(-0.5*sq((x-xo)/1.)) - y)

int main() {
	L0 = 20.;
        Re = 1e6, Fr = 0.4;
	Y0 = -16;
	rho2=1000/RHO, mu2=1./Re;
	rho1=1/RHO, mu1=mu2;
	G.y = - 1/sq(Fr);
  	Z.y = Heau;
	DT = 0.005;
	init_grid (1 << 6); 
	run();
}

/**
## Boundary Conditions
*/
/**
Our numerical experiment we use slip condition at the bottom and neumann at the right. Then we use a straight velocity profile at the inlet.
*/
u.n[left] = dirichlet(U0);
//u.n[right] = neumann(0.);
//u.t[right] = dirichlet(0.);

u.n[bottom] = neumann(0.);
u.t[bottom] = neumann(0.);

/**
Embedded boundary Conditions
*/
u.n[embed] = neumann(0.);
u.t[embed] = neumann(0.);

/**
## Initial conditions
*/
/**
A zero-velocity field is initialized with a water level of Heau. Then a bump at the bottom of the water.
*/
event init (t = 0){
	foreach(){
  		foreach_dimension()
			u.x[] = 0.;
  	}
  	fraction(f, (y - Heau));
        boundary({f,u});
    	vertex scalar phi[];
  	foreach_vertex(){
    		phi[] = -bump;
	}
  	boundary ({phi});
  	fractions (phi, cs, fs);
        system("rm -f lign* out* all-out*");
}
/**
## Mesh adaptation
*/
/**
Each timestep, the grid is adapted with respect to the wavelet-based estimated discretization error for the representation of fraction field, the pressure field and the representation of the embedded boundary (cs)
*/
event adapt (i++){
	adapt_wavelet ((scalar*){f, cs, u},
		 (double[]){0.001, 0.001, 0.05, 0.05}, maxlevel);
}
/**
## Outputs
*/
/**
video interface water/air + u.y
*/
event bviewer (t+=0.1 ; t<=EndTime) {
	clear();
        view();
        box();
	draw_vof ("cs","fs", filled = -1);
        cells();
        save ("refinement.mp4");
        clear();
        view(tx = -0.5, ty = 0.2);
        box();
        draw_vof ("cs","fs", filled = -1);
        draw_vof ("f", lw = 8); 
	squares ("u.y", linear = true);
	save ("vawes.mp4");
}
/**
Gnuplot parameters
*/
FILE * gnuplotPipe;
event init (t = 0){
  gnuplotPipe = popen ("gnuplot", "w");
  fprintf(gnuplotPipe,
	  "set term pngcairo\n"
	  "set xr [0 : 20.]\n"
	  "set yr [0. : 2.]\n"
	  "set key top right\n"
	  "set grid\n"
	  "set xlabel 'x'\n"
	  "set ylabel 'y'\n");
}
/**
We use output_facets to extract the coordinate (x,y) of the interface 
*/
int frame = 0;
event amplitude (t+=0.1 ; t<=EndTime){
  	char names[80];
	sprintf(names, "outt%d", pid());
	FILE * fout = fopen (names, "w");
	output_facets (f,fout);
	fclose(fout);
        system("cat outt* > all-out.dat");
  	double Xmax = 0., Ymax = 0., Xmin = 0., Ymin = 0.;
  /**
  We extract Xmax, Ymax, Xmin, Ymin for each time step
  */
        if(pid() == 0.){
		system("LC_ALL=C awk 'NF==2 && $2<1.5' all-out.dat > all-out2.dat");//filtrer valeurs > 1.5
		system("LC_ALL=C sort -nrk2 all-out2.dat | head -1 > ligne");//output ymax
		system("LC_ALL=C awk 'NF==2 && $1==15.' all-out2.dat > xh.dat");// output the coordinate of the interface at (x=15,y) x>xo
		system("LC_ALL=C cat ligne >> lignes");//copie (x,ymax)
                system("LC_ALL=C sort -nk2 all-out2.dat | head -1 > min");//output (x,ymin)
		FILE * fligne = fopen("ligne", "r");
		rewind(fligne);
		fscanf(fligne,"%lf %lf", &Xmax, &Ymax);
		fclose(fligne);
		FILE * fmin = fopen("min", "r");
		rewind(fmin);
		fscanf(fmin,"%lf %lf", &Xmin, &Ymin);
		fclose(fmin);
            /**
  We calculate evolution peak to peak amplitude of waves
  */
		static FILE * famp = fopen("ampl","w");
		fprintf(famp ,"%g %g\n", t, Ymax-Ymin);
		fflush(famp);
          /**
          We calculate the shallow water velocity U(x,ymax,t) = $$\sqrt(gh(x,ymax,t))$$
          */
		double fbump;
		fbump = (1./(1.*sqrt(2*M_PI)))*exp(-0.5*sq((Xmax-xo)/1.));
		static FILE * fg = fopen("fond","w");
		fprintf(fg ,"%g %g %g\n", t, Ymax - fbump, sqrt((abs(G.y))*(Ymax - fbump)));
		fflush(fg);
          	double xh = 0., yh = 0.;
		FILE * fxhh = fopen("xh.dat", "r");
		rewind(fxhh);
		fscanf(fxhh,"%lf %lf", &xh, &yh);
          /**Here we calculate the speed Up to the point (xh,yh) after the bump. Then the wavelength is calculated with the measured speed and the speed Uo. */
#if 1
		static FILE * fxx = fopen("xhh.dat","w");
		double Up, kl, kd, kdt, klt;
          	Up = interpolate (u.x, xh, yh);
          /**For a stationnary wave, the value of the wavelengths should be close. A relative error (%) calculation is then made and the standing wave wavelengths are recorded.*/
		if(Up<1e2){
			kd = sqrt(abs(G.y)/sq(Up));
			kdt = sqrt(abs(G.y)/sq(U0));
			kl = sqrt((yh - Up/abs(G.y))*(3./pow(yh,3)));
			klt = sqrt((yh - U0/abs(G.y))*(3./pow(yh,3)));
			if((kd-kdt)/kdt*100.<=30. || (kl-klt)/klt*100. <=30.){
				fprintf(fxx ,"%g %g %g %g %g %g %g\n", t, xh, yh,kd ,(kd-kdt)/kdt*100., kl, (kl-klt)/klt*100.);
				fflush(fxx);
				fclose(fxx);
			}
			else{
				fprintf(fxx, "critere non respecté%g\n",t);
				fflush(fxx);	
			}
		}
		else{
			fprintf(fxx, "bug%g \t %g \t %g \t %g\n", t, Up, xh,yh);
			fflush(fxx);
		}
#endif
        }
  /**
  We make a video of the interface using output_facets and gnuplot
  */
	fprintf (gnuplotPipe, "set output 'plot%d.png'\n", frame);
	fprintf (gnuplotPipe, "set title 't = %g, Xmax = %.2lf, Ymax =%.2lf' font ',15'\n",t, Xmax, Ymax);
	fprintf (gnuplotPipe, "plot 'all-out2.dat' u 1:2 w l lt rgb'#11BB11' t 'interface',""'ligne' u 1:2 t 'Position max crête'\n");
	fflush (gnuplotPipe);
	frame++;
  /**
  We calculate c crest velocity(x,ymax,t) $\leq$ U shallow water (x,ymax,t)
  */
	static FILE * f1 = fopen ("cmax", "w");
	if(interpolate (u.x, Xmax, Ymax) < 1e2){
		fprintf(f1,"%g %g\n", t, interpolate (u.x, Xmax, Ymax));
		fflush(f1);
	}

}
event stop (t = EndTime){
        system("ffmpeg -r 25 -f image2 -i plot%d.png -c:v libx264 -vf format=yuv420p -y mov.mp4 && "
	 "rm -f plot* ligne");
        return 1;
}
/**
if the wave is stationary, the phase velocity is equal to V=U0.
if the interpolation works we get the Lighthill's wavelength $$k_{0} = \sqrt(3/h^{2}(1-V^{2}/gh))$$.
Or using the deep water theory : $$k=\sqrt(g/U0^{2})$$.
*/



/**
## Results
We check that U(x,ymax,t) shallow water is greater than c(x,ymax,t) with c equal to the peak velocity
~~~gnuplot
set output "Evolution_Umax.png"
reset
set xlabel 'times t'
set ylabel 'Velocity'
set title 'Velocity(X,Ymax,t) evolution'
plot 'cmax' using 1:2 with lines t 'max peak velocity c',\
      'fond' u 1:3 w l t 'shallow water speed U'
~~~
We calculate the evolution of the amplitude which corresponds according to James Lighthill F(ko)
~~~gnuplot
set output "amplitude.png"
reset
set xlabel 'times t'
set ylabel 'Amplitude'
set title 'Evolution peak to peak amplitude interface'
plot 'ampl' u 1:2 w l t 'using outputfacets'
~~~
~~~gnuplot
set output "interf.png"
reset
set xlabel 'x'
set ylabel 'y'
set title 'interface t=EndTime'
plot 'all-out2.dat' u 1:2 w l t 'using outputfacets'
~~~

![fraction field.](vagues/vawes.mp4)
![refinement.](vagues/refinement.mp4)
![evolution interface.](vagues/mov.mp4)
## Reference
J. Lighthill. Waves in Fluids. Cambridge University Press, 1978.
*/