CFLAGS += -O2 -disable-dimensions
include $(BASILISK)/Makefile.defs

#collapsewall.tst: collapsewall2.tst

#collapsewall2.c: collapsewall.c
#	ln -sf collapsewall.c collapsewall2.c
#collapsewall.s: CFLAGS += -DCASE2=1
#collapsewall.tst: CFLAGS += -DCASE2=1
