name: Sync from Darcs

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Darcs
        run: |
          echo "Installing Darcs following official methods from darcs.net..."
          
          # Method 1: Install using Stack (preferred method according to darcs.net)
          echo "Installing Stack..."
          curl -sSL https://get.haskellstack.org/ | sh
          
          echo "Installing Darcs with Stack..."
          stack install darcs
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Check if Darcs was installed successfully
          if command -v darcs &> /dev/null; then
            echo "Darcs installed successfully using Stack"
            darcs --version
          else
            echo "Stack installation failed, trying with Cabal..."
            
            # Method 2: Install using Cabal as fallback
            sudo apt-get update
            sudo apt-get install -y ghc cabal-install
            cabal update
            
            echo "Installing Darcs with Cabal..."
            cabal install darcs
            export PATH="$HOME/.cabal/bin:$PATH"
            echo "$HOME/.cabal/bin" >> $GITHUB_PATH
            
            # Verify installation
            if command -v darcs &> /dev/null; then
              echo "Darcs installed successfully using Cabal"
              darcs --version
            else
              echo "Failed to install Darcs. Exiting."
              exit 1
            fi
          fi

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Pull from Darcs
        run: |
          darcs pull --all
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changes exist
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add -A
          git commit -m "Auto-update from Darcs repository"
          git push 