name: Sync from Darcs

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Darcs from Ubuntu package
        run: |
          # Try to install Darcs from Ubuntu package first
          sudo apt-get update
          sudo apt-get install -y darcs || true
          
          # If that fails, try installing from source with specific Cabal version
          if ! command -v darcs &> /dev/null; then
            echo "Installing Darcs from source..."
            sudo apt-get install -y ghc cabal-install
            cabal update
            
            # Try different versions of Darcs
            for version in 2.16.5 2.14.2 2.12.5 2.10.2; do
              echo "Trying Darcs version $version..."
              if cabal install darcs-$version; then
                echo "Successfully installed Darcs $version"
                break
              fi
            done
            
            echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          fi

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Pull from Darcs
        run: |
          darcs pull --all
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changes exist
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add -A
          git commit -m "Auto-update from Darcs repository"
          git push 